name: React Flask API
parameters:
  UsernamePrefix:
    description: Prefix to use for username
    type: string
    default: devsplacePlus
  Password:
    description: Its your password
    type: string
    default: 12345678
execConfig:
  environment:
    RANDOM_ENV: Devspace
endpoints:
  TimeEndpoint:
    port: 5000
    protocol: HTTPS
    path: time
dependsOn: []
