name: React Flask API
execConfig:
  environment:
    RANDOM_ENV: Devspace
    API2_TIME_URL: ${API2.TimeEndpoint.host}/${API2.TimeEndpoint.path}
endpoints:
  TimeEndpoint:
    port: 5000
    protocol: HTTPS
    path: api-1-time
dependsOn:
  API2:
    type: DEVSPACES::REPO::GIT
    properties:
      repoUrl: https://github.com/abhishek-dhanraj-TI/react-flask-api/tree/ui-api-api-2
